database:
 name: rslims
 user: dba
 password: rsdba
 host: rslims.jax.org

user:
  username: chent
  password: Steve19981230

azure:
   email: tianyu.chen@jax.org
   access token: lymulontolyct3ct5zn7zr5ubmkahcxzkumonczqoqhckrrbt4pa
   base_url: https://dev.azure.com/jacksonlaboratory
   team: Teams\\Research\\KOMP

archive: \\jax.org\jax\phenotype\OMERO\KOMP\Archive\

transfer_to_omero:
    src: \\jax.org\jax\phenotype\OMERO\KOMP\ImagesToBeImportedIntoOmero
    dest: \\jax.org\jax\omero-drop\dropbox
    log_path: C:/Program Files/KOMP/SoftwareUtilities/exec_logs/import_to_omero_log
    submission_form_name: OMERO_submission_form.xlsx
    group_owner: whitej
    wk_group: KOMP_eye

    Eye:
      OD: "Right eye"
      OS: "Left Eye"
      OU: "Both"

    TEST:
      fundus2: Eye Morphology
      path: Gross Pathology
      fundus: ERG
      Slit: Eye Morphology

transfer_to_lims:
    log_path: C:/Program Files/KOMP/SoftwareUtilities/exec_logs/import_to_jaxlims_log
    TEST:
      fundus2: Eye Morphology
      path: Gross Pathology
      fundus: ERG
      Slit: Eye Morphology

    procedureDefVersionKey:
      Gross Pathology: 230
      Eye Morphology: 231
      ERG: 254

    dest:
      Eye Morphology: \\jax.org\jax\phenotype\EYE-MORPHOLOGY\KOMP\images-omero
      Gross Pathology: \\jax.org\jax\phenotype\GrossPathology\KOMP\images-omero
      ERG: \\jax.org\jax\phenotype\ERG-V2\KOMP\images-omero
