database:
 name: rslims
 user: dba
 password: rsdba
 host: rslims.jax.org

user:
  username: chent
  password: Ql4nc,tzjzsblj!

azure:
   email: tianyu.chen@jax.org
   access token: oakw5774hgrc5zfzmotwzx3ryettwqvwoftpfqxwanwhb2bsw4va
   base_url: https://dev.azure.com/jacksonlaboratory
   team: Teams\\Research\\KOMP

app:
  log_path1: C:/Program Files/KOMP/SoftwareUtilities/exec_logs/import_to_omero_log
  log_path2: C:/Program Files/KOMP/SoftwareUtilities/exec_logs/import_to_jaxlims_log
  submission_form_name: OMERO_submission_form.xlsx
  group_owner: whitej
  wk_group: komp_eye

  Eye:
    OD: "Right eye"
    OS: "Left Eye"
    OU: "Both"

  TEST:
    fundus2: Eye Morphology
    path: Gross Pathology
    fundus: ERG
    Slit: Eye Morphology

  procedureDefVersionKey:
    Gross Pathology: 230
    Eye Morphology: 231
    ERG: 254

